spring.application.name=pharmacy-system


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
logging.file.name=logs/pharmacy-system.log
logging.file.path=./logs
logging.level.com.pharmacy=DEBUG